export interface IAdvanceSearchProperties {
  ID_Usuario: string,
  ID_Abogado: string,
  ID_AbogadoAlterno: string,
  ID_AbogadoAlterno1: string,
  Identificacion: string,
  NombreSolicitante: string,
  RNL: string,
  RNC: string,
  NombreComercial: string,
  IdentificacionPersonaFisica: string,
  NombrePersonaFisica: string,
  RepresentanteLegalEmpleador: string,
  ID_InstanciaJudicial: string,
  ID_FaseProceso: string,
}